language: java
sudo: required

services:
  - docker

before_install:
  - mvn clean package
  - docker build --tag=shifty .
  - docker-compose up

script:
  - docker ps | grep shiftyspring_wildfly_1
  - docker ps | grep shiftyspring_db_1
